config/routes.rb
Rails.application.routes.draw do
 	
	 resources :urls
  root 'urls#index'

  get 'url/index'
  post 'urls/new' => "urls#create"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url.rb
class Url < ApplicationRecord
validates :long, :short, uniqueness: true
before_validation :shorten, on: :create

	def shorten
		self.short = ('a'..'z').to_a.shuffle[0,2].join << SecureRandom.hex(1)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  before_action :show_url, only: [:show]

  def index
  	@url = Url.all
  end

  def new
  	@url = Url.new
  end

  def show
  	redirect_to @url.long
  end

  def create
  	@url = Url.new(url_params)

		respond_to do |format|
      if @url.save
        format.html { redirect_to urls_path, notice: 'Url was successfully created.' }
        format.json { render :show, status: :created, location: @url }
      else
        render 'new'
      end
    end
  end

  private
  	def url_params
  		params.require(:url).permit(:long, :short)
  	end

    def show_url
      if params[:id].to_i == 0
        @url = Url.find_by(short: "#{params[:id]}")
      else
        @url = Url.find_by(id: params[:id])
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortener</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/urls/index.html.erb
<h1>Urls</h1>

<table>
  <tr>
    <th>Long URL</th>
    <th>Shortened URL</th>
    <th>URL ID</th>
    <th colspan="3"></th>
  </tr>
 
  <% Url.all.each do |url| %>
    <tr>
      <td><%= url.long %></td>
      <td><%= url.short %></td>
      <td><%= url.id %></td>
      <td><%= link_to 'show', url %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'New url', new_url_path %>

app/views/urls/new.html.erb
<%= form_with model: @url, local: true do |form| %>
 
  <div>
    <%=form.label :"enter URL" %>
    <%= form.text_field :long, id: :url_long %>
  </div>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/urls/show.html.erb
  <h2>Show Url</h2>
<table>
  <tr>
    <th>Long URL</th>
    <th>Shortened URL</th>
    <th>URL ID</th>
    <th colspan="3"></th>
  </tr>

  <% Url.all.each do |url| %>
    <tr>
      <td><%= url.long %></td>
      <td><%= url.short %></td>
      <td><%= url.id %></td>
    </tr>
  <% end %>
</table>